--- 
title: "Reddy: An open-source package for analyzing eddy-covariance data"
author: ""
date: "" #"`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: noctiluc3nt/Reddy
description: ""
---


# Introduction

<hr>
<span style="color: darkblue;">**An introduction to eddy-covariance measurements and their meteorological evaluation**</span> <br>
**Package**: <a href="https://github.com/noctiluc3nt/Reddy">Reddy package (Github)</a> <br>
**Gitbook**: <a href="https://github.com/noctiluc3nt/ec_analyze/tree/main/notebooks">jupyter notebooks (Github)</a>
<hr>

Eddy-covariance measurements represent the standard approach to measure turbulent fluxes, which are central in exchange processes between atmosphere and land/vegetation/cryosphere/hydrosphere. 
<br>



**Measurement setup:** <br>
The measurements are performed with a fast-sampling sonic, that measures all three wind components and temperature based on the propagation speed of sound. 
Additionally, gas analyzers can be used to measure trace gas fluxes (water vapor, carbon, dioxide, methane, ...). 
The instruments can be mounted at a tower or mast with one or several heights.


[Figure]


**Data sources:** <br>
There are several coordinated FLUXNETs, which coordinate and standardise eddy-covariance measurements regionally or globally and provide post-processed flux data. For example:<br>

- FLUXNET
- ICOS (Integrated Carbon Observation System)